FROM quay.io/keycloak/keycloak:latest
ENV KC_DB=postgres
WORKDIR /opt/keycloak

# Add extensions
ADD --chown=keycloak:keycloak https://github.com/klausbetz/apple-identity-provider-keycloak/releases/download/1.14.0/apple-identity-provider-1.14.0.jar /opt/keycloak/providers/apple-identity-provider-1.14.0.jar
ADD --chown=keycloak:keycloak https://github.com/smeetsee/keycloak-protocol-cas/releases/download/26.2.4/keycloak-protocol-cas-26.2.4.jar /opt/keycloak/providers/keycloak-protocol-cas-26.2.4.jar
ADD --chown=keycloak:keycloak https://github.com/wadahiro/keycloak-discord/releases/download/v0.6.1/keycloak-discord-0.6.1.jar /opt/keycloak/providers/keycloak-discord-0.6.1.jar
ADD --chown=keycloak:keycloak https://github.com/eosc-kc/keycloak-orcid/releases/download/1.4.0/keycloak-orcid.jar /opt/keycloak/providers/keycloak-orcid.jar

# Build Keycloak
RUN /opt/keycloak/bin/kc.sh build
